subscriptions:
  # Form population events
  - resourceType: QuestionnaireResponse
    topicName: form.populated
    owner: 'form-auto-population-service'
    supportedInteractions:
      - create
      - update
    description: 'Form population completion events'
    kafkaTopic: 'form.populated'
