name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affected.outputs.affected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Get affected projects
        id: affected
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            AFFECTED=$(npx nx show projects --affected --base=origin/${{ github.base_ref }} --head=HEAD --json)
          else
            AFFECTED=$(npx nx show projects --affected --base=HEAD~1 --json)
          fi
          echo "affected=$AFFECTED" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.affected != '[]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx nx affected -t lint --base=origin/${{ github.base_ref }} --head=HEAD
          else
            npx nx affected -t lint --base=HEAD~1
          fi

  typecheck:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.affected != '[]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx nx affected -t vite:typecheck --base=origin/${{ github.base_ref }} --head=HEAD
          else
            npx nx affected -t vite:typecheck --base=HEAD~1
          fi

  test:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.affected != '[]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx nx affected -t test --base=origin/${{ github.base_ref }} --head=HEAD --coverage
          else
            npx nx affected -t test --base=HEAD~1 --coverage
          fi

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.affected != '[]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build affected projects
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx nx affected -t build --base=origin/${{ github.base_ref }} --head=HEAD
          else
            npx nx affected -t build --base=HEAD~1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts
          path: |
            dist/
            !dist/**/*.map
          retention-days: 7

  quality-gate:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test, build]
    if: always()
    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ needs.lint.result }}" == "failure" || "${{ needs.typecheck.result }}" == "failure" || "${{ needs.test.result }}" == "failure" || "${{ needs.build.result }}" == "failure" ]]; then
            echo "One or more quality checks failed"
            exit 1
          fi
          echo "All quality checks passed"
